# Site settings
title:
email: team@acmutsa.org
author:
description: >-
  This is the ACM UTSA description
baseurl: https://github.com/UTSA-ACM/acmutsa.github.io
url: http://acmutsa.github.io

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: UTSA-ACM
twitter_username: acmutsa

# plugins
plugins: [jekyll-paginate]
paginate: 3
